-- Add/modify columns 
alter table PJWZ_PARTS_UNLOAD_REGISTER modify UNLOAD_TRAINTYPE_IDX VARCHAR2(50 CHAR);
alter table PJWZ_PARTS_UNLOAD_REGISTER modify UNLOAD_REPAIR_CLASS_IDX VARCHAR2(50 CHAR);
alter table PJWZ_PARTS_UNLOAD_REGISTER modify UNLOAD_REPAIR_TIME_IDX VARCHAR2(50 CHAR);

-- Add/modify columns 
alter table PJWZ_PARTS_FIX_REGISTER modify ABOARD_TRAINTYPE_IDX VARCHAR2(50 CHAR);
alter table PJWZ_PARTS_FIX_REGISTER modify ABOARD_REPAIR_CLASS_IDX VARCHAR2(50 CHAR);
alter table PJWZ_PARTS_FIX_REGISTER modify ABOARD_REPAIR_TIME_IDX VARCHAR2(50 CHAR);


