-- Add/modify columns 
alter table PJJX_PARTS_RDP modify UNLOAD_TRAINTYPE_IDX VARCHAR2(50 CHAR);
alter table PJJX_PARTS_RDP modify UNLOAD_REPAIR_CLASS_IDX VARCHAR2(50 CHAR);
alter table PJJX_PARTS_RDP modify UNLOAD_REPAIR_TIME_IDX VARCHAR2(50 CHAR);
