insert into EOS_DICT_TYPE (DICTTYPEID, DICTTYPENAME, RANK, PARENTID, SEQNO)
values ('FREIGHT_SYS', '货车运用', 1, '', '.FREIGHT_SYS.');

insert into EOS_DICT_TYPE (DICTTYPEID, DICTTYPENAME, RANK, PARENTID, SEQNO)
values ('PASSENGER_SYS', '客车运用', 1, '', '.PASSENGER_SYS.');

insert into EOS_DICT_TYPE (DICTTYPEID, DICTTYPENAME, RANK, PARENTID, SEQNO)
values ('FREIGHT_WORKTYPE', '作业方式', 2, 'FREIGHT_SYS', '.FREIGHT_SYS.FREIGHT_WORKTYPE.');

insert into EOS_DICT_TYPE (DICTTYPEID, DICTTYPENAME, RANK, PARENTID, SEQNO)
values ('FREIGHT_WORKNATURE', '作业性质', 2, 'FREIGHT_SYS', '.FREIGHT_SYS.FREIGHT_WORKNATURE.');

insert into EOS_DICT_TYPE (DICTTYPEID, DICTTYPENAME, RANK, PARENTID, SEQNO)
values ('DAYNIGHT_TYPE', '白夜班', 2, 'FREIGHT_SYS', '.FREIGHT_SYS.DAYNIGHT_TYPE.');

insert into EOS_DICT_TYPE (DICTTYPEID, DICTTYPENAME, RANK, PARENTID, SEQNO)
values ('CLASS_TYPE', '班次', 2, 'FREIGHT_SYS', '.FREIGHT_SYS.CLASS_TYPE.');

insert into EOS_DICT_TYPE (DICTTYPEID, DICTTYPENAME, RANK, PARENTID, SEQNO)
values ('DETAIN_TRAIN_TYPE', '扣车类型', 2, 'FREIGHT_SYS', '.FREIGHT_SYS.DETAIN_TRAIN_TYPE.');

insert into EOS_DICT_TYPE (DICTTYPEID, DICTTYPENAME, RANK, PARENTID, SEQNO)
values ('INSPECTION_LEVEL', '列检所等级', 2, 'FREIGHT_SYS', '.FREIGHT_SYS.INSPECTION_LEVEL.');

insert into EOS_DICT_TYPE (DICTTYPEID, DICTTYPENAME, RANK, PARENTID, SEQNO)
values ('FAULT_TYPE', '故障类型', 2, 'FREIGHT_SYS', '.FREIGHT_SYS.FAULT_TYPE.');

insert into EOS_DICT_TYPE (DICTTYPEID, DICTTYPENAME, RANK, PARENTID, SEQNO)
values ('VEHICLE_KIND_FREIGHT', '车型种类', 2, 'FREIGHT_SYS', '.FREIGHT_SYS.VEHICLE_KIND_FREIGHT.');

insert into EOS_DICT_TYPE (DICTTYPEID, DICTTYPENAME, RANK, PARENTID, SEQNO)
values ('VEHICLE_KIND_PASSENGER', '车型种类', 2, 'PASSENGER_SYS', '.PASSENGER_SYS.VEHICLE_KIND_PASSENGER.');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('VEHICLE_KIND_PASSENGER', 'VEHICLE_KIND_PASSENGER_30', '硬座', 1, 3, 1, '', '.VEHICLE_KIND_PASSENGER_30.', '', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('VEHICLE_KIND_PASSENGER', 'VEHICLE_KIND_PASSENGER_40', '硬卧', 1, 4, 1, '', '.VEHICLE_KIND_PASSENGER_40.', '', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('VEHICLE_KIND_PASSENGER', 'VEHICLE_KIND_PASSENGER_10', '餐车', 1, 2, 1, '', '.VEHICLE_KIND_PASSENGER_10.', '', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('VEHICLE_KIND_PASSENGER', 'VEHICLE_KIND_PASSENGER_20', '客车', 1, 1, 1, '', '.VEHICLE_KIND_PASSENGER_20.', '', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('FREIGHT_WORKTYPE', 'DYNAMIC_CHECK', '动态检查', 1, 2, 1, '', '.DYNAMIC_CHECK.', '', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('FREIGHT_WORKTYPE', 'MANMACHINE_CHECK', '人机分工检查', 1, 3, 1, '', '.MANMACHINE_CHECK.', '', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('FREIGHT_WORKNATURE', 'ARRIVE_TYPE', '到达作业', 1, 1, 1, '', '.ARRIVE_TYPE.', '30', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('FREIGHT_WORKNATURE', 'TRANSIT_TYPE', '中转作业', 1, 3, 1, '', '.TRANSIT_TYPE.', '50', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('CLASS_TYPE', 'CLASS_ONE', '07:30~12:00', 1, 1, 1, '', '.CLASS_ONE.', '', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('CLASS_TYPE', 'CLASS_TWO', '12:00~17:30', 1, 2, 1, '', '.CLASS_TWO.', '', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('CLASS_TYPE', 'CLASS_THREE', '17:30~00:00', 1, 3, 1, '', '.CLASS_THREE.', '', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('CLASS_TYPE', 'CLASS_FOUR', '00:00~07:30', 1, 4, 1, '', '.CLASS_FOUR.', '', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('DETAIN_TRAIN_TYPE', '10', '到期检修', 1, 1, 1, '', '.10.', '', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('DETAIN_TRAIN_TYPE', '20', '转临修', 1, 2, 1, '', '.20.', '', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('FREIGHT_WORKNATURE', 'DEPARTURE_TYPE', '始发作业', 1, 2, 1, '', '.DEPARTURE_TYPE.', '40', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('FREIGHT_WORKNATURE', 'PASS_TYPE', '通过作业', 1, 4, 1, '', '.PASS_TYPE.', '60', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('DAYNIGHT_TYPE', 'DAY_TYPE', '白班', 1, 1, 1, '', '.DAY_TYPE.', '', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('DAYNIGHT_TYPE', 'NIGHT_TYPE', '夜班', 1, 2, 1, '', '.NIGHT_TYPE.', '', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('INSPECTION_LEVEL', '10', '特级', 1, 1, 1, '', '.10.', '', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('INSPECTION_LEVEL', '20', '一级', 1, 2, 1, '', '.20.', '', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('INSPECTION_LEVEL', '30', '二级', 1, 3, 1, '', '.30.', '', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('VEHICLE_KIND_FREIGHT', 'VEHICLE_KIND_FREIGHT_10', '篷车', 1, 1, 1, '', '.VEHICLE_KIND_FREIGHT_10.', '', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('VEHICLE_KIND_FREIGHT', 'VEHICLE_KIND_FREIGHT_20', '罐车', 1, 2, 1, '', '.VEHICLE_KIND_FREIGHT_20.', '', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('VEHICLE_KIND_FREIGHT', 'VEHICLE_KIND_FREIGHT_30', '煤车', 1, 3, 1, '', '.VEHICLE_KIND_FREIGHT_30.', '', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('FAULT_TYPE', 'FAULT_CLASSIFY', '典型故障', 1, 1, 1, '', '.FAULT_CLASSIFY.', '', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('FAULT_TYPE', 'FAULT_CLOSEDOOR', '制动故障关门车', 1, 2, 1, '', '.FAULT_CLOSEDOOR.', '', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('FREIGHT_WORKTYPE', 'MANUAL_CHECK', '人工检查', 1, 1, 1, '', '.MANUAL_CHECK.', '', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('FAULT_TYPE', 'FAULT_WHEEL', '车轮踏面故障', 1, 3, 1, '', '.FAULT_WHEEL.', '', '');

insert into EOS_DICT_ENTRY (DICTTYPEID, DICTID, DICTNAME, STATUS, SORTNO, RANK, PARENTID, SEQNO, FILTER1, FILTER2)
values ('FAULT_TYPE', 'FAULT_OTHER', '其它', 1, 4, 1, '', '.FAULT_OTHER.', '', '');



