<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%String ctx = request.getContextPath();%>
/**
 * extjs按钮控件引用的图标样式
 */
.addIcon{		background-image:url(<%=ctx %>/frame/resources/images/toolbar/add.png) !important;}
.editIcon{		background-image:url(<%=ctx %>/frame/resources/images/toolbar/page_edit_1.png) !important;}
.saveIcon{		background-image:url(<%=ctx %>/frame/resources/images/toolbar/save.gif) !important;}
.cancelIcon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/no.gif) !important;}
.deleteIcon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/delete.png) !important;}
.yesIcon{		background-image:url(<%=ctx %>/frame/resources/images/toolbar/yes.png) !important;}
.refreshIcon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/refresh.png) !important;}
.refreshgif{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/refresh.gif) !important;}
.searchIcon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/search.png) !important;}
.chart_organisationIcon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/chart_organisation.png) !important;}
.keyIcon{	    background-image:url(<%=ctx %>/frame/resources/images/toolbar/key.png) !important;}
.resetIcon{		background-image:url(<%=ctx %>/frame/resources/images/toolbar/tbar_synchronize.png) !important;}
.archiveIcon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/im.png) !important;}
.chart_attributeConfigIcon{		background-image:url(<%=ctx %>/frame/resources/images/toolbar/config.png) !important;}
.application_view_listIcon{	    background-image:url(<%=ctx %>/frame/resources/images/toolbar/application_view_list.png) !important;}
.control_play_blueIcon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/control_play_blue.png) !important;	}
.tbar_synchronizeIcon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/tbar_synchronize.png) !important;	}
.cupIcon{			background-image:url(<%=ctx %>/frame/resources/images/toolbar/cup.png) !important;	}
.database_connectIcon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/database_connect.png) !important;	}
.bookIcon{			background-image:url(<%=ctx %>/frame/resources/images/toolbar/book.png) !important;	}
.tableIcon{			background-image:url(<%=ctx %>/frame/resources/images/toolbar/table.png) !important;	}
.dustbinIcon{			background-image:url(<%=ctx %>/frame/resources/images/toolbar/dustbin.gif) !important;	}
.acceptIcon{			background-image:url(<%=ctx %>/frame/resources/images/toolbar/accept.png) !important;	}
.edit1Icon{			background-image:url(<%=ctx %>/frame/resources/images/toolbar/edit1.png) !important;	}
.application_goIcon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/application_go.png) !important;	}
.printerIcon{			background-image:url(<%=ctx %>/frame/resources/images/toolbar/printer.png) !important;	}
.cogIcon{			background-image:url(<%=ctx %>/frame/resources/images/toolbar/cog.png) !important;	}
.cmpIcon{			background-image:url(<%=ctx %>/frame/resources/images/toolbar/cmp.gif) !important;	}
.pageIcon{			background-image:url(<%=ctx %>/frame/resources/images/toolbar/page.png) !important;	}
.gridIcon{			background-image:url(<%=ctx %>/frame/resources/images/toolbar/grid.png) !important;	}
.checkIcon{			background-image:url(<%=ctx %>/frame/resources/images/toolbar/check.png) !important;	}
.uploadIcon{			background-image:url(<%=ctx %>/frame/resources/images/toolbar/upload.png) !important;	}
.downloadIcon{			background-image:url(<%=ctx %>/frame/resources/images/toolbar/download.png) !important;	}
.page_edit_1Icon{			background-image:url(<%=ctx %>/frame/resources/images/toolbar/page_edit_1.png) !important;	}
.page_excelIcon{			background-image:url(<%=ctx %>/frame/resources/images/toolbar/page_excel.png) !important;	}
.application_view_listIcon{			background-image:url(<%=ctx %>/frame/resources/images/toolbar/application_view_list.png) !important;	}
.nextIcon{  	background-image:url(<%=ctx %>/frame/resources/images/toolbar/page-next.gif) !important;}
.prevIcon{  	background-image:url(<%=ctx %>/frame/resources/images/toolbar/page-prev.gif) !important;}
.closeIcon{  	background-image:url(<%=ctx %>/frame/resources/images/toolbar/cross.gif) !important;}
.configIcon{  	background-image:url(<%=ctx %>/frame/resources/images/toolbar/config.png) !important;}
.attachIcon{ 	background-image:url(<%=ctx %>/frame/resources/images/toolbar/attach.gif) !important;}
.pjglIcon{ 	background-image:url(<%=ctx %>/frame/resources/images/toolbar/pjgl.gif) !important;}
.page-first{ 	background-image:url(<%=ctx %>/frame/resources/images/toolbar/page-first.gif) !important;}
.page-last{ 	background-image:url(<%=ctx %>/frame/resources/images/toolbar/page-last.gif) !important;}
.page-first-disabled{ 	background-image:url(<%=ctx %>/frame/resources/images/toolbar/page-first-disabled.gif) !important;}
.page-last-disabled{ 	background-image:url(<%=ctx %>/frame/resources/images/toolbar/page-last-disabled.gif) !important;}
.pluginIcon{ 	background-image:url(<%=ctx %>/frame/resources/images/toolbar/plugin.gif) !important;}
.icon-expand-all{ 	background-image:url(<%=ctx %>/frame/resources/images/toolbar/expand-all.gif) !important;}
.icon-collapse-all{ 	background-image:url(<%=ctx %>/frame/resources/images/toolbar/collapse-all.gif) !important;}
.wrenchIcon{ 	background-image:url(<%=ctx %>/frame/resources/images/toolbar/wrench.png) !important;}
.leafIcon{		background-image:url(<%=ctx %>/frame/resources/images/toolbar/leaf.gif) !important;}
.theme2Icon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/theme2.png) !important;}
.messageIcon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/message.png) !important;}
.startIcon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/start.png) !important;}
.lockIcon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/lock.png) !important;}
.unlockIcon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/unlock.gif) !important;}
.x-grid-record-red table{ background: red; }    
.queryIcon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/search.gif) !important;}
.commentsIcon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/comments.png) !important;}
.beginIcon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/begin.png) !important;}
.see1Icon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/seeFile.png) !important;}
.see2Icon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/seeFile2.png) !important;}
.judge1Icon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/award_star_gold_1.png) !important;}
.judge2Icon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/award_star_gold_2.png) !important;}
.judge3Icon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/award_star_gold_3.png) !important;}
.usergrayIcon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/user_gray.png) !important;}
.userfemaleIcon {	background-image:url(<%=ctx %>/frame/resources/images/toolbar/user_female.png) !important;}
.userIcon {	background-image:url(<%=ctx %>/frame/resources/images/toolbar/status_online.png) !important;}
.examineIcon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/window_caise_list.png) !important;}
.home1Icon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/application_home.png) !important;}
.home2Icon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/home.png) !important;}
.groupIcon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/group.png) !important;}
.gold1Icon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/medal_gold_1.png) !important;}
.gold2Icon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/medal_gold_2.png) !important;}
.gold3Icon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/medal_gold_3.png) !important;}
.silver1Icon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/medal_silver_1.png) !important;}
.silver2Icon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/medal_silver_2.png) !important;}
.silver3Icon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/medal_silver_3.png) !important;}
.tableRefreshIcon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/table_refresh.png) !important;}
.folderUserIcon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/folder_user.png) !important;}
.userSuitIcon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/user_suit.png) !important;}
.buildingIcon{	background-image:url(<%=ctx %>/frame/resources/images/toolbar/building.png) !important;}

