package com.yunda.frame.yhgl.entity;

import java.util.Date;

/**
 * AcApplication generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class AcApplication implements java.io.Serializable {

	// Fields

	private Long appid;

	private String appcode;

	private String appname;

	private String apptype;

	private String isopen;

	private Date opendate;

	private String url;

	private String appdesc;

	private Long maintenance;

	private String manarole;

	private String demo;

	private String iniwp;

	private String intaskcenter;

	private String ipaddr;

	private String ipport;

	// Constructors

	/** default constructor */
	public AcApplication() {
	}

	/** full constructor */
	public AcApplication(String appcode, String appname, String apptype,
			String isopen, Date opendate, String url, String appdesc,
			Long maintenance, String manarole, String demo, String iniwp,
			String intaskcenter, String ipaddr, String ipport) {
		this.appcode = appcode;
		this.appname = appname;
		this.apptype = apptype;
		this.isopen = isopen;
		this.opendate = opendate;
		this.url = url;
		this.appdesc = appdesc;
		this.maintenance = maintenance;
		this.manarole = manarole;
		this.demo = demo;
		this.iniwp = iniwp;
		this.intaskcenter = intaskcenter;
		this.ipaddr = ipaddr;
		this.ipport = ipport;
	}

	// Property accessors

	public Long getAppid() {
		return this.appid;
	}

	public void setAppid(Long appid) {
		this.appid = appid;
	}

	public String getAppcode() {
		return this.appcode;
	}

	public void setAppcode(String appcode) {
		this.appcode = appcode;
	}

	public String getAppname() {
		return this.appname;
	}

	public void setAppname(String appname) {
		this.appname = appname;
	}

	public String getApptype() {
		return this.apptype;
	}

	public void setApptype(String apptype) {
		this.apptype = apptype;
	}

	public String getIsopen() {
		return this.isopen;
	}

	public void setIsopen(String isopen) {
		this.isopen = isopen;
	}

	public Date getOpendate() {
		return this.opendate;
	}

	public void setOpendate(Date opendate) {
		this.opendate = opendate;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getAppdesc() {
		return this.appdesc;
	}

	public void setAppdesc(String appdesc) {
		this.appdesc = appdesc;
	}

	public Long getMaintenance() {
		return this.maintenance;
	}

	public void setMaintenance(Long maintenance) {
		this.maintenance = maintenance;
	}

	public String getManarole() {
		return this.manarole;
	}

	public void setManarole(String manarole) {
		this.manarole = manarole;
	}

	public String getDemo() {
		return this.demo;
	}

	public void setDemo(String demo) {
		this.demo = demo;
	}

	public String getIniwp() {
		return this.iniwp;
	}

	public void setIniwp(String iniwp) {
		this.iniwp = iniwp;
	}

	public String getIntaskcenter() {
		return this.intaskcenter;
	}

	public void setIntaskcenter(String intaskcenter) {
		this.intaskcenter = intaskcenter;
	}

	public String getIpaddr() {
		return this.ipaddr;
	}

	public void setIpaddr(String ipaddr) {
		this.ipaddr = ipaddr;
	}

	public String getIpport() {
		return this.ipport;
	}

	public void setIpport(String ipport) {
		this.ipport = ipport;
	}

}