package com.yunda.frame.yhgl.entity;

/**
 * AcFunction generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class AcFunction implements java.io.Serializable {
    
    // Modified by hetao on 2016-04-11 增加应用功能类型常量
    /** 应用功能类型 - 前端功能 */
    public static final String FUNC_TYPE_PAGE = "前端功能";
    /** 应用功能类型 - 报表功能 */
    public static final String FUNC_TYPE_REPORT = "报表功能";
    /** 应用功能类型 - 后台服务 */
    public static final String FUNC_TYPE_SERVICE = "后台服务";
    
    /** 功能编号 */
    private String funccode;
    
    /** 功能组编号 */
    private Long funcgroupid;
    
    /** 功能名称 */
    private String funcname;
    
    /** 功能描述 */
    private String funcdesc;
    
    /** 功能调用入口 */
    private String funcaction;
    
    /** 输入参数 */
    private String parainfo;
    
    /** 是否验证权限 */
    private String ischeck;
    
    /** 功能类型 */
    private String functype;
    
    /** 可否定义为菜单 */
    private String ismenu;
    
    // -------------------Add Properties Start ------------------
    private String funcgroupname;
    
    private long appid;
    
    private String appname;
    
    // -------------------Add Properties End ------------------
    // Constructors
    
    /** default constructor */
    public AcFunction() {
    }
    
    /** minimal constructor */
    public AcFunction(String funcname) {
        this.funcname = funcname;
    }
    
    /** full constructor */
    public AcFunction(Long funcgroupid, String funcname, String funcdesc, String funcaction, String parainfo, String ischeck, String functype,
        String ismenu) {
        this.funcgroupid = funcgroupid;
        this.funcname = funcname;
        this.funcdesc = funcdesc;
        this.funcaction = funcaction;
        this.parainfo = parainfo;
        this.ischeck = ischeck;
        this.functype = functype;
        this.ismenu = ismenu;
    }
    
    /** getCollection constructor */
    public AcFunction(String funccode, String funcname, String funcaction, long funcgroupid, String funcgroupname, long appid, String appname) {
        this.funccode = funccode; // 功能代码
        this.funcname = funcname; // 功能名称
        this.funcaction = funcaction; // 功能调用入口
        this.funcgroupid = funcgroupid; // 功能组ID
        this.funcgroupname = funcgroupname; // 功能组名称
        this.appid = appid; // 应用ID
        this.appname = appname; // 应用名称
    }
    
    // Property accessors
    
    public String getFunccode() {
        return this.funccode;
    }
    
    public void setFunccode(String funccode) {
        this.funccode = funccode;
    }
    
    public Long getFuncgroupid() {
        return this.funcgroupid;
    }
    
    public void setFuncgroupid(Long funcgroupid) {
        this.funcgroupid = funcgroupid;
    }
    
    public String getFuncname() {
        return this.funcname;
    }
    
    public void setFuncname(String funcname) {
        this.funcname = funcname;
    }
    
    public String getFuncdesc() {
        return this.funcdesc;
    }
    
    public void setFuncdesc(String funcdesc) {
        this.funcdesc = funcdesc;
    }
    
    public String getFuncaction() {
        return this.funcaction;
    }
    
    public void setFuncaction(String funcaction) {
        this.funcaction = funcaction;
    }
    
    public String getParainfo() {
        return this.parainfo;
    }
    
    public void setParainfo(String parainfo) {
        this.parainfo = parainfo;
    }
    
    public String getIscheck() {
        return this.ischeck;
    }
    
    public void setIscheck(String ischeck) {
        this.ischeck = ischeck;
    }
    
    public String getFunctype() {
        return this.functype;
    }
    
    public void setFunctype(String functype) {
        this.functype = functype;
    }
    
    public String getIsmenu() {
        return this.ismenu;
    }
    
    public void setIsmenu(String ismenu) {
        this.ismenu = ismenu;
    }
    
    public long getAppid() {
        return appid;
    }
    
    public void setAppid(long appid) {
        this.appid = appid;
    }
    
    public String getAppname() {
        return appname;
    }
    
    public void setAppname(String appname) {
        this.appname = appname;
    }
    
    public String getFuncgroupname() {
        return funcgroupname;
    }
    
    public void setFuncgroupname(String funcgroupname) {
        this.funcgroupname = funcgroupname;
    }
    
}
