package com.yunda.frame.yhgl.entity;

/**
 * AcFuncresource generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class AcFuncresource implements java.io.Serializable {

	// Fields

	private Long resid;

	private String funccode;

	private String restype;

	private String respath;

	private String compackname;

	private String resname;

	// Constructors

	/** default constructor */
	public AcFuncresource() {
	}

	/** full constructor */
	public AcFuncresource(String funccode, String restype, String respath,
			String compackname, String resname) {
		this.funccode = funccode;
		this.restype = restype;
		this.respath = respath;
		this.compackname = compackname;
		this.resname = resname;
	}

	// Property accessors

	public Long getResid() {
		return this.resid;
	}

	public void setResid(Long resid) {
		this.resid = resid;
	}

	public String getFunccode() {
		return this.funccode;
	}

	public void setFunccode(String funccode) {
		this.funccode = funccode;
	}

	public String getRestype() {
		return this.restype;
	}

	public void setRestype(String restype) {
		this.restype = restype;
	}

	public String getRespath() {
		return this.respath;
	}

	public void setRespath(String respath) {
		this.respath = respath;
	}

	public String getCompackname() {
		return this.compackname;
	}

	public void setCompackname(String compackname) {
		this.compackname = compackname;
	}

	public String getResname() {
		return this.resname;
	}

	public void setResname(String resname) {
		this.resname = resname;
	}

}