package com.yunda.frame.yhgl.entity;

/**
 * AcFuncgroup generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class AcFuncgroup implements java.io.Serializable {

	// Fields

	private Long funcgroupid;

	private Long appid;

	private String funcgroupname;

	private Long parentgroup;

	private Long grouplevel;

	private String funcgroupseq;

	private String isleaf;

	private Long subcount;

	// Constructors

	/** default constructor */
	public AcFuncgroup() {
	}

	/** minimal constructor */
	public AcFuncgroup(Long appid) {
		this.appid = appid;
	}

	/** full constructor */
	public AcFuncgroup(Long appid, String funcgroupname, Long parentgroup,
			Long grouplevel, String funcgroupseq, String isleaf, Long subcount) {
		this.appid = appid;
		this.funcgroupname = funcgroupname;
		this.parentgroup = parentgroup;
		this.grouplevel = grouplevel;
		this.funcgroupseq = funcgroupseq;
		this.isleaf = isleaf;
		this.subcount = subcount;
	}

	// Property accessors

	public Long getFuncgroupid() {
		return this.funcgroupid;
	}

	public void setFuncgroupid(Long funcgroupid) {
		this.funcgroupid = funcgroupid;
	}

	public Long getAppid() {
		return this.appid;
	}

	public void setAppid(Long appid) {
		this.appid = appid;
	}

	public String getFuncgroupname() {
		return this.funcgroupname;
	}

	public void setFuncgroupname(String funcgroupname) {
		this.funcgroupname = funcgroupname;
	}

	public Long getParentgroup() {
		return this.parentgroup;
	}

	public void setParentgroup(Long parentgroup) {
		this.parentgroup = parentgroup;
	}

	public Long getGrouplevel() {
		return this.grouplevel;
	}

	public void setGrouplevel(Long grouplevel) {
		this.grouplevel = grouplevel;
	}

	public String getFuncgroupseq() {
		return this.funcgroupseq;
	}

	public void setFuncgroupseq(String funcgroupseq) {
		this.funcgroupseq = funcgroupseq;
	}

	public String getIsleaf() {
		return this.isleaf;
	}

	public void setIsleaf(String isleaf) {
		this.isleaf = isleaf;
	}

	public Long getSubcount() {
		return this.subcount;
	}

	public void setSubcount(Long subcount) {
		this.subcount = subcount;
	}

}