package com.yunda.frame.yhgl.entity;


/**
 * AcMenu generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class AcMenu implements java.io.Serializable {
	/** 菜单编号 */
	private String menuid;
	/** 菜单名称 */
	private String menuname;
	/** 菜单显示（中文） */
	private String menulabel;
	/** 菜单代码 */
	private String menucode;
	/** 是否叶子菜单 */
	private String isleaf;
	/** 功能调用入口 */
	private String menuaction;
	/** 输入参数(暂未使用)*/
	private String parameter;
	/** UI入口(暂未使用) */
	private String uientry;
	/** 菜单层次 */
	private Long menulevel;
	/** 根菜单(暂未使用) */
	private String rootid;
	/** 父菜单编号 */
	private String parentsid;
	/** 显示顺序 */
	private Long displayorder;
	/** 菜单闭合图片路径(暂未使用) */
	private String imagepath;
	/** 菜单展开图片路径(暂未使用) */
	private String expandpath;
	/** 菜单路径序列 */
	private String menuseq;
	/** 页面打开方式 */
	private String openmode;
	/** 子节点数 */
	private Long subcount;
	/** 应用编号 */
	private Long appid;
	/** 功能编号 */
	private String funccode;
	

	// Constructors

	/** default constructor */
	public AcMenu() {
	}

	/** minimal constructor */
	public AcMenu(String menuname, String menulabel) {
		this.menuname = menuname;
		this.menulabel = menulabel;
	}

	/** full constructor */
	public AcMenu(String menuname, String menulabel, String menucode,
			String isleaf, String menuaction, String parameter, String uientry,
			Long menulevel, String rootid, String parentsid, Long displayorder,
			String imagepath, String expandpath, String menuseq,
			String openmode, Long subcount, Long appid, String funccode) {
		this.menuname = menuname;
		this.menulabel = menulabel;
		this.menucode = menucode;
		this.isleaf = isleaf;
		this.menuaction = menuaction;
		this.parameter = parameter;
		this.uientry = uientry;
		this.menulevel = menulevel;
		this.rootid = rootid;
		this.parentsid = parentsid;
		this.displayorder = displayorder;
		this.imagepath = imagepath;
		this.expandpath = expandpath;
		this.menuseq = menuseq;
		this.openmode = openmode;
		this.subcount = subcount;
		this.appid = appid;
		this.funccode = funccode;
	}

	// Property accessors

	public String getMenuid() {
		return this.menuid;
	}

	public void setMenuid(String menuid) {
		this.menuid = menuid;
	}

	public String getMenuname() {
		return this.menuname;
	}

	public void setMenuname(String menuname) {
		this.menuname = menuname;
	}

	public String getMenulabel() {
		return this.menulabel;
	}

	public void setMenulabel(String menulabel) {
		this.menulabel = menulabel;
	}

	public String getMenucode() {
		return this.menucode;
	}

	public void setMenucode(String menucode) {
		this.menucode = menucode;
	}

	public String getIsleaf() {
		return this.isleaf;
	}

	public void setIsleaf(String isleaf) {
		this.isleaf = isleaf;
	}

	public String getMenuaction() {
		return this.menuaction;
	}

	public void setMenuaction(String menuaction) {
		this.menuaction = menuaction;
	}

	public String getParameter() {
		return this.parameter;
	}

	public void setParameter(String parameter) {
		this.parameter = parameter;
	}

	public String getUientry() {
		return this.uientry;
	}

	public void setUientry(String uientry) {
		this.uientry = uientry;
	}

	public Long getMenulevel() {
		return this.menulevel;
	}

	public void setMenulevel(Long menulevel) {
		this.menulevel = menulevel;
	}

	public String getRootid() {
		return this.rootid;
	}

	public void setRootid(String rootid) {
		this.rootid = rootid;
	}

	public String getParentsid() {
		return this.parentsid;
	}

	public void setParentsid(String parentsid) {
		this.parentsid = parentsid;
	}

	public Long getDisplayorder() {
		return this.displayorder;
	}

	public void setDisplayorder(Long displayorder) {
		this.displayorder = displayorder;
	}

	public String getImagepath() {
		return this.imagepath;
	}

	public void setImagepath(String imagepath) {
		this.imagepath = imagepath;
	}

	public String getExpandpath() {
		return this.expandpath;
	}

	public void setExpandpath(String expandpath) {
		this.expandpath = expandpath;
	}

	public String getMenuseq() {
		return this.menuseq;
	}

	public void setMenuseq(String menuseq) {
		this.menuseq = menuseq;
	}

	public String getOpenmode() {
		return this.openmode;
	}

	public void setOpenmode(String openmode) {
		this.openmode = openmode;
	}

	public Long getSubcount() {
		return this.subcount;
	}

	public void setSubcount(Long subcount) {
		this.subcount = subcount;
	}

	public Long getAppid() {
		return this.appid;
	}

	public void setAppid(Long appid) {
		this.appid = appid;
	}

	public String getFunccode() {
		return this.funccode;
	}

	public void setFunccode(String funccode) {
		this.funccode = funccode;
	}
}