package com.yunda.frame.yhgl.entity;

import java.util.Date;

/**
 * AcOperator generated by MyEclipse Persistence Tools
 * 系统登录用户表
 */

@SuppressWarnings("serial")
public class AcOperator implements java.io.Serializable {

	// Fields

	private Long operatorid;  //操作员ID 

	private String userid;  //登录用户名

	private String password; //密码

	private Date invaldate; //密码失效日期

	private String operatorname; //操作员名称

	private String authmode; //认证模式

	private String status; //操作员状态

	private Date unlocktime; //解锁时间

	private String menutype; // 菜单风格

	private Date lastlogin; // 最后一次登录时间

	private Long errcount; // 最新登录次数

	private Date startdate; //有效开始时间

	private Date enddate; // 有效结束时间

	private String validtime; //有效时间范围

	private String maccode; //MAC码

	private String ipaddress; // iP地址

	private String email; // 邮箱

	// Constructors

	/** default constructor */
	public AcOperator() {
	}

	/** minimal constructor */
	public AcOperator(String userid) {
		this.userid = userid;
	}

	public AcOperator(String userid,String operatorname) {
		this.userid = userid;
		this.operatorname = operatorname;
	}

	/** full constructor */
	public AcOperator(String userid, String password, Date invaldate,
			String operatorname, String authmode, String status,
			Date unlocktime, String menutype, Date lastlogin, Long errcount,
			Date startdate, Date enddate, String validtime, String maccode,
			String ipaddress, String email) {
		this.userid = userid;
		this.password = password;
		this.invaldate = invaldate;
		this.operatorname = operatorname;
		this.authmode = authmode;
		this.status = status;
		this.unlocktime = unlocktime;
		this.menutype = menutype;
		this.lastlogin = lastlogin;
		this.errcount = errcount;
		this.startdate = startdate;
		this.enddate = enddate;
		this.validtime = validtime;
		this.maccode = maccode;
		this.ipaddress = ipaddress;
		this.email = email;
	}

	// Property accessors

	public Long getOperatorid() {
		return this.operatorid;
	}

	public void setOperatorid(Long operatorid) {
		this.operatorid = operatorid;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getInvaldate() {
		return this.invaldate;
	}

	public void setInvaldate(Date invaldate) {
		this.invaldate = invaldate;
	}

	public String getOperatorname() {
		return this.operatorname;
	}

	public void setOperatorname(String operatorname) {
		this.operatorname = operatorname;
	}

	public String getAuthmode() {
		return this.authmode;
	}

	public void setAuthmode(String authmode) {
		this.authmode = authmode;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getUnlocktime() {
		return this.unlocktime;
	}

	public void setUnlocktime(Date unlocktime) {
		this.unlocktime = unlocktime;
	}

	public String getMenutype() {
		return this.menutype;
	}

	public void setMenutype(String menutype) {
		this.menutype = menutype;
	}

	public Date getLastlogin() {
		return this.lastlogin;
	}

	public void setLastlogin(Date lastlogin) {
		this.lastlogin = lastlogin;
	}

	public Long getErrcount() {
		return this.errcount;
	}

	public void setErrcount(Long errcount) {
		this.errcount = errcount;
	}

	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	public String getValidtime() {
		return this.validtime;
	}

	public void setValidtime(String validtime) {
		this.validtime = validtime;
	}

	public String getMaccode() {
		return this.maccode;
	}

	public void setMaccode(String maccode) {
		this.maccode = maccode;
	}

	public String getIpaddress() {
		return this.ipaddress;
	}

	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
}