package com.yunda.frame.yhgl.entity;


/**
 * AcOperatorrole generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class AcOperatorrole implements java.io.Serializable {

	// Fields

	private AcOperatorroleId id;

	private String auth;
	

	// Constructors

	/** default constructor */
	public AcOperatorrole() {
	}

	/** minimal constructor */
	public AcOperatorrole(AcOperatorroleId id) {
		this.id = id;
	}

	/** full constructor */
	public AcOperatorrole(AcOperatorroleId id, String auth) {
		this.id = id;
		this.auth = auth;
	}

	// Property accessors

	public AcOperatorroleId getId() {
		return this.id;
	}

	public void setId(AcOperatorroleId id) {
		this.id = id;
	}

	public String getAuth() {
		return this.auth;
	}

	public void setAuth(String auth) {
		this.auth = auth;
	}

}