package com.yunda.frame.yhgl.entity;


/**
 * AcRolefunc generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class AcRolefunc implements java.io.Serializable {

	// Fields

	private AcRolefuncId id;

	private Long appid;

	private Long funcgroupid;
	
	private String roleid; //附加字段

	private String funccode; //附加字段

	// Constructors

	/** default constructor */
	public AcRolefunc() {
	}

	/** full constructor */
	public AcRolefunc(AcRolefuncId id, Long appid, Long funcgroupid) {
		this.id = id;
		this.appid = appid;
		this.funcgroupid = funcgroupid;
	}
	
	public AcRolefunc(Long appid, Long funcgroupid, String roleid, String funccode){
		this.appid = appid;
		this.funcgroupid = funcgroupid;
		this.roleid = roleid; 
		this.funccode = funccode;
	}

	// Property accessors

	public AcRolefuncId getId() {
		return this.id;
	}

	public void setId(AcRolefuncId id) {
		this.id = id;
	}

	public Long getAppid() {
		return this.appid;
	}

	public void setAppid(Long appid) {
		this.appid = appid;
	}

	public Long getFuncgroupid() {
		return this.funcgroupid;
	}

	public void setFuncgroupid(Long funcgroupid) {
		this.funcgroupid = funcgroupid;
	}

	public String getFunccode() {
		return funccode;
	}

	public void setFunccode(String funccode) {
		this.funccode = funccode;
	}

	public String getRoleid() {
		return roleid;
	}

	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

}