package com.yunda.frame.yhgl.entity;

/**
 * AcRole generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class AcRole implements java.io.Serializable {

	// Fields

	private String roleid;

	private String rolename;

	private String roletype;

	private String roledesc;

	private Long appid;

	// Constructors

	/** default constructor */
	public AcRole() {
	}

	/** full constructor */
	public AcRole(String rolename, String roletype, String roledesc, Long appid) {
		this.rolename = rolename;
		this.roletype = roletype;
		this.roledesc = roledesc;
		this.appid = appid;
	}

	// Property accessors

	public String getRoleid() {
		return this.roleid;
	}

	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	public String getRoletype() {
		return this.roletype;
	}

	public void setRoletype(String roletype) {
		this.roletype = roletype;
	}

	public String getRoledesc() {
		return this.roledesc;
	}

	public void setRoledesc(String roledesc) {
		this.roledesc = roledesc;
	}

	public Long getAppid() {
		return this.appid;
	}

	public void setAppid(Long appid) {
		this.appid = appid;
	}

}