package com.yunda.frame.yhgl.entity;

/**
 * EosDictEntryId generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class EosDictEntryId implements java.io.Serializable {

	// Fields

	private String dicttypeid;

	private String dictid;

	// Constructors

	/** default constructor */
	public EosDictEntryId() {
	}

	/** full constructor */
	public EosDictEntryId(String dicttypeid, String dictid) {
		this.dicttypeid = dicttypeid;
		this.dictid = dictid;
	}

	// Property accessors

	public String getDicttypeid() {
		return this.dicttypeid;
	}

	public void setDicttypeid(String dicttypeid) {
		this.dicttypeid = dicttypeid;
	}

	public String getDictid() {
		return this.dictid;
	}

	public void setDictid(String dictid) {
		this.dictid = dictid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EosDictEntryId))
			return false;
		EosDictEntryId castOther = (EosDictEntryId) other;

		return ((this.getDicttypeid() == castOther.getDicttypeid()) || (this
				.getDicttypeid() != null
				&& castOther.getDicttypeid() != null && this.getDicttypeid()
				.equals(castOther.getDicttypeid())))
				&& ((this.getDictid() == castOther.getDictid()) || (this
						.getDictid() != null
						&& castOther.getDictid() != null && this.getDictid()
						.equals(castOther.getDictid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getDicttypeid() == null ? 0 : this.getDicttypeid()
						.hashCode());
		result = 37 * result
				+ (getDictid() == null ? 0 : this.getDictid().hashCode());
		return result;
	}

}