package com.yunda.frame.yhgl.entity;

import java.util.Set;

/**
 * OmDuty generated by MyEclipse Persistence Tools
 * 职务表
 */

@SuppressWarnings("serial")
public class OmDuty implements java.io.Serializable {

	// Fields

	private Long dutyid;//职务ID

	//private OmDuty omDuty; //父职务
	
	private Long parentduty ;//父职务ID

	private String dutycode; //职务代码

	private String dutyname; //职务名称

	private Long dutylevel;//职务层次

	private String dutyseq; //职务序列号

	private String dutytype; //职务套别

	private String isleaf; //是否叶子节点

	private Long subcount; //子节点数

	private String remark; //备注

//	private Set omPositions = new HashSet(0); //岗位/职位
//
//	private Set omDuties = new HashSet(0);  //子职务

	// Constructors
	
	private String parentdutyname;//附加字段：上级职务名称

	/** default constructor */
	public OmDuty() {
	}

	/**
	 * <li>说明：获取职务实体， 加入虚拟临时字段parentdutyname，职务列表查询采用
	 * <li>创建人：谭诚
	 * <li>创建日期：2013-11-26
	 * <li>修改人： 
	 * <li>修改日期：
	 */
	public OmDuty(Long dutyid, Long parentduty, String dutycode, String dutyname, Long dutylevel, String dutyseq, String dutytype, String isleaf, Long subcount, String remark, String parentdutyname) {
		this.dutyid = dutyid;
		this.parentduty = parentduty;
		this.dutycode = dutycode;
		this.dutyname = dutyname;
		this.dutylevel = dutylevel;
		this.dutyseq = dutyseq;
		this.dutytype = dutytype;
		this.isleaf = isleaf;
		this.subcount = subcount;
		this.remark = remark;
		this.parentdutyname = parentdutyname; //上级职务名称
	}

	/** full constructor */
	
	// Property accessors

	public Long getDutyid() {
		return this.dutyid;
	}

	public OmDuty(Long dutyid, Long parentduty, String dutycode,
			String dutyname, Long dutylevel, String dutyseq, String dutytype,
			String isleaf, Long subcount, String remark, Set omPositions,
			Set omDuties) {
		this.dutyid = dutyid;
		this.parentduty = parentduty;
		this.dutycode = dutycode;
		this.dutyname = dutyname;
		this.dutylevel = dutylevel;
		this.dutyseq = dutyseq;
		this.dutytype = dutytype;
		this.isleaf = isleaf;
		this.subcount = subcount;
		this.remark = remark;
	}

	public void setDutyid(Long dutyid) {
		this.dutyid = dutyid;
	}

	

	public String getDutycode() {
		return this.dutycode;
	}

	public void setDutycode(String dutycode) {
		this.dutycode = dutycode;
	}

	public String getDutyname() {
		return this.dutyname;
	}

	public void setDutyname(String dutyname) {
		this.dutyname = dutyname;
	}

	public Long getDutylevel() {
		return this.dutylevel;
	}

	public void setDutylevel(Long dutylevel) {
		this.dutylevel = dutylevel;
	}
  
	public Long getParentduty() {
		return parentduty;
	}

	public void setParentduty(Long parentduty) {
		this.parentduty = parentduty;
	}

	public String getDutyseq() {
		return this.dutyseq;
	}

	public void setDutyseq(String dutyseq) {
		this.dutyseq = dutyseq;
	}

	public String getDutytype() {
		return this.dutytype;
	}

	public void setDutytype(String dutytype) {
		this.dutytype = dutytype;
	}

	public String getIsleaf() {
		return this.isleaf;
	}

	public void setIsleaf(String isleaf) {
		this.isleaf = isleaf;
	}

	public Long getSubcount() {
		return this.subcount;
	}

	public void setSubcount(Long subcount) {
		this.subcount = subcount;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getParentdutyname() {
		return parentdutyname;
	}

	public void setParentdutyname(String parentdutyname) {
		this.parentdutyname = parentdutyname;
	}

//	public Set getOmPositions() {
//		return this.omPositions;
//	}
//
//	public void setOmPositions(Set omPositions) {
//		this.omPositions = omPositions;
//	}
//
//	public Set getOmDuties() {
//		return this.omDuties;
//	}
//
//	public void setOmDuties(Set omDuties) {
//		this.omDuties = omDuties;
//	}

}