package com.yunda.frame.yhgl.entity;


/**
 * OmEmpgroup generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class OmEmpgroup implements java.io.Serializable {

	// Fields

	private OmEmpgroupId id;

	// Constructors

	/** default constructor */
	public OmEmpgroup() {
	}

	/** full constructor */
	public OmEmpgroup(OmEmpgroupId id) {
		this.id = id;
	}

	// Property accessors

	public OmEmpgroupId getId() {
		return this.id;
	}

	public void setId(OmEmpgroupId id) {
		this.id = id;
	}

}