package com.yunda.frame.yhgl.entity;


/**
 * OmEmpposition generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class OmEmpposition implements java.io.Serializable {

	// Fields

	private OmEmppositionId id;

	private String ismain;

	// Constructors

	/** default constructor */
	public OmEmpposition() {
	}


	public OmEmpposition(OmEmppositionId id) {
		super();
		this.id = id;
	}



	// Property accessors

	public OmEmppositionId getId() {
		return this.id;
	}

	public void setId(OmEmppositionId id) {
		this.id = id;
	}

	

	public String getIsmain() {
		return this.ismain;
	}

	public void setIsmain(String ismain) {
		this.ismain = ismain;
	}

}