package com.yunda.frame.yhgl.entity;

/**
 * OmEmpgroupId generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class OmEmpgroupId implements java.io.Serializable {

	// Fields

	private Long groupid;

	private Long empid;

	// Constructors

	/** default constructor */
	public OmEmpgroupId() {
	}

	/** full constructor */
	public OmEmpgroupId(Long groupid, Long empid) {
		this.groupid = groupid;
		this.empid = empid;
	}

	// Property accessors

	public Long getGroupid() {
		return this.groupid;
	}

	public void setGroupid(Long groupid) {
		this.groupid = groupid;
	}

	public Long getEmpid() {
		return this.empid;
	}

	public void setEmpid(Long empid) {
		this.empid = empid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OmEmpgroupId))
			return false;
		OmEmpgroupId castOther = (OmEmpgroupId) other;

		return ((this.getGroupid() == castOther.getGroupid()) || (this
				.getGroupid() != null
				&& castOther.getGroupid() != null && this.getGroupid().equals(
				castOther.getGroupid())))
				&& ((this.getEmpid() == castOther.getEmpid()) || (this
						.getEmpid() != null
						&& castOther.getEmpid() != null && this.getEmpid()
						.equals(castOther.getEmpid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getGroupid() == null ? 0 : this.getGroupid().hashCode());
		result = 37 * result
				+ (getEmpid() == null ? 0 : this.getEmpid().hashCode());
		return result;
	}

}