package com.yunda.frame.yhgl.entity;

/**
 * OmEmppositionId generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class OmEmppositionId implements java.io.Serializable {

	// Fields

	private Long positionid;

	private Long empid;

	// Constructors

	/** default constructor */
	public OmEmppositionId() {
	}

	/** full constructor */
	public OmEmppositionId(Long positionid, Long empid) {
		this.positionid = positionid;
		this.empid = empid;
	}

	// Property accessors

	public Long getPositionid() {
		return this.positionid;
	}

	public void setPositionid(Long positionid) {
		this.positionid = positionid;
	}

	public Long getEmpid() {
		return this.empid;
	}

	public void setEmpid(Long empid) {
		this.empid = empid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OmEmppositionId))
			return false;
		OmEmppositionId castOther = (OmEmppositionId) other;

		return ((this.getPositionid() == castOther.getPositionid()) || (this
				.getPositionid() != null
				&& castOther.getPositionid() != null && this.getPositionid()
				.equals(castOther.getPositionid())))
				&& ((this.getEmpid() == castOther.getEmpid()) || (this
						.getEmpid() != null
						&& castOther.getEmpid() != null && this.getEmpid()
						.equals(castOther.getEmpid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPositionid() == null ? 0 : this.getPositionid()
						.hashCode());
		result = 37 * result
				+ (getEmpid() == null ? 0 : this.getEmpid().hashCode());
		return result;
	}

}