package com.yunda.frame.yhgl.entity;


/**
 * OmEmporg generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class OmEmporg implements java.io.Serializable {

	// Fields 

	private OmEmporgId id;  //机构ID 
	private String ismain;  //是否主机构     1为 主机构  2 为非主机构

	// Constructors

	/** default constructor */
	public OmEmporg() {
	}
  
	public OmEmporg(OmEmporgId id) {
		this.id = id;
	}

	// Property accessors

	public OmEmporgId getId() {
		return this.id;
	}

	public void setId(OmEmporgId id) {
		this.id = id;
	}



	public String getIsmain() {
		return this.ismain;
	}

	public void setIsmain(String ismain) {
		this.ismain = ismain;
	}

}