package com.yunda.frame.yhgl.entity;


/**
 * OmGroupposi generated by MyEclipse Persistence Tools
 * 工作组岗位列表（工作组和岗位的中间表）
 */

@SuppressWarnings("serial")
public class OmGroupposi implements java.io.Serializable {

	// Fields

	private OmGroupposiId id; //主键



	// Constructors

	/** default constructor */
	public OmGroupposi() {
	}
  
	
	public OmGroupposi(OmGroupposiId id) {
		this.id = id;
	}


	
	public OmGroupposiId getId() {
		return this.id;
	}

	public void setId(OmGroupposiId id) {
		this.id = id;
	}


	

}