package com.yunda.frame.yhgl.entity;

import java.util.Date;

/**
 * OmGroup generated by MyEclipse Persistence Tools
 * 工作组
 * 
 */

@SuppressWarnings("serial")
public class OmGroup implements java.io.Serializable {

	// Fields

	private Long groupid;  //  工作组ID

	//private OmGroup omGroup;  // 父工作组
	
	private Long parentgroupid;
 
	private Long orgid;     //隶属机构编号

	private Long grouplevel; //工作组层次

	private String groupname; //工作组名称

	private String groupdesc; //工作组描述

	private String grouptype; //工作组类型

	private String groupseq; //工作组路径序列

	private Date startdate; //工作组有效开始日期

	private Date enddate;//工作组有效截止日期

	private String groupstatus; //工作组状态

	private String manager;//负责人

	private Date createtime; //创建时间

	private Date lastupdate; //最近更新时间

	private Long updator; //最近更新人员

	private String isleaf; //是否叶子节点

	private Long subcount; //子节点数
	
	private String empname;//负责人姓名

	//private Set omGroupposis = new HashSet(0);

	//private Set omGroups = new HashSet(0); //子工作组数
	
	private Long empid; //人员ID

	// Constructors
	public OmGroup(Long groupid, Long parentgroupid, Long orgid, Long grouplevel, String groupname, String groupdesc, String grouptype,
			String groupseq, Date startdate, Date enddate, String groupstatus, String manager, Date createtime, Date lastupdate,
			Long updator, String isleaf, Long subcount, String empname){
		this.groupid = groupid;
		this.parentgroupid = parentgroupid;
		this.orgid = orgid;
		this.grouplevel = grouplevel;
		this.groupname = groupname;
		this.groupdesc = groupdesc;
		this.grouptype = grouptype;
		this.groupseq = groupseq;
		this.startdate = startdate;
		this.enddate = enddate;
		this.groupstatus = groupstatus;
		this.manager = manager;
		this.createtime = createtime;
		this.lastupdate = lastupdate;
		this.updator = updator;
		this.isleaf = isleaf;
		this.subcount = subcount;
		this.empname = empname; //通过OmGroup-OmEmpgroup-OmEmployee的关联关系， 将人员姓名注入
	}
	
	/**
	 * 人员管理-工作组调动列表
	 */
	public OmGroup(Long empid, String empname, Long groupid, String groupname){
		this.empid = empid;
		this.empname = empname;
		this.groupid = groupid;
		this.groupname = groupname;
	}
	

	/** default constructor */
	public OmGroup() {
	}

	
	// Property accessors

	public Long getGroupid() {
		return this.groupid;
	}

	public void setGroupid(Long groupid) {
		this.groupid = groupid;
	}

	

	public Long getOrgid() {
		return this.orgid;
	}

	public void setOrgid(Long orgid) {
		this.orgid = orgid;
	}

	public Long getGrouplevel() {
		return this.grouplevel;
	}

	public void setGrouplevel(Long grouplevel) {
		this.grouplevel = grouplevel;
	}

	public String getGroupname() {
		return this.groupname;
	}
  
	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}
	public Long getParentgroupid() {
		return parentgroupid;
	}

	public void setParentgroupid(Long parentgroupid) {
		this.parentgroupid = parentgroupid;
	}

	public String getGroupdesc() {
		return this.groupdesc;
	}

	public void setGroupdesc(String groupdesc) {
		this.groupdesc = groupdesc;
	}

	public String getGrouptype() {
		return this.grouptype;
	}

	public void setGrouptype(String grouptype) {
		this.grouptype = grouptype;
	}

	public String getGroupseq() {
		return this.groupseq;
	}

	public void setGroupseq(String groupseq) {
		this.groupseq = groupseq;
	}

	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	public String getGroupstatus() {
		return this.groupstatus;
	}

	public void setGroupstatus(String groupstatus) {
		this.groupstatus = groupstatus;
	}

	public String getManager() {
		return this.manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getLastupdate() {
		return this.lastupdate;
	}

	public void setLastupdate(Date lastupdate) {
		this.lastupdate = lastupdate;
	}

	public Long getUpdator() {
		return this.updator;
	}

	public void setUpdator(Long updator) {
		this.updator = updator;
	}

	public String getIsleaf() {
		return this.isleaf;
	}

	public void setIsleaf(String isleaf) {
		this.isleaf = isleaf;
	}

	public Long getSubcount() {
		return this.subcount;
	}

	public void setSubcount(Long subcount) {
		this.subcount = subcount;
	}


	/**
	 * <li>说明：
	 * <li>返回值： the empname
	 */
	public String getEmpname() {
		return empname;
	}


	/**
	 * <li>说明：
	 * <li>参数： empname
	 */
	public void setEmpname(String empname) {
		this.empname = empname;
	}

	public Long getEmpid() {
		return empid;
	}

	public void setEmpid(Long empid) {
		this.empid = empid;
	}
}