package com.yunda.frame.yhgl.entity;

/**
 * OmGroupposiId generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class OmGroupposiId implements java.io.Serializable {

	// Fields

	private Long groupid;

	private Long positionid;

	// Constructors

	/** default constructor */
	public OmGroupposiId() {
	}

	/** full constructor */
	public OmGroupposiId(Long groupid, Long positionid) {
		this.groupid = groupid;
		this.positionid = positionid;
	}

	// Property accessors

	public Long getGroupid() {
		return this.groupid;
	}

	public void setGroupid(Long groupid) {
		this.groupid = groupid;
	}

	public Long getPositionid() {
		return this.positionid;
	}

	public void setPositionid(Long positionid) {
		this.positionid = positionid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OmGroupposiId))
			return false;
		OmGroupposiId castOther = (OmGroupposiId) other;

		return ((this.getGroupid() == castOther.getGroupid()) || (this
				.getGroupid() != null
				&& castOther.getGroupid() != null && this.getGroupid().equals(
				castOther.getGroupid())))
				&& ((this.getPositionid() == castOther.getPositionid()) || (this
						.getPositionid() != null
						&& castOther.getPositionid() != null && this
						.getPositionid().equals(castOther.getPositionid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getGroupid() == null ? 0 : this.getGroupid().hashCode());
		result = 37
				* result
				+ (getPositionid() == null ? 0 : this.getPositionid()
						.hashCode());
		return result;
	}

}