package com.yunda.frame.yhgl.entity;

/**
 * OmPartyroleId generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class OmPartyroleId implements java.io.Serializable {

	// Fields

	private String roleid;  //角色ID

	private String partytype; //类型 0  组织机构  1 工作组   2 岗位  3 职位

	private Long partyid; //分别对应上面四种对象的ID 

	// Constructors

	/** default constructor */
	public OmPartyroleId() {
	}

	/** full constructor */
	public OmPartyroleId(String roleid, String partytype, Long partyid) {
		this.roleid = roleid;
		this.partytype = partytype;
		this.partyid = partyid;
	}

	// Property accessors

	public String getRoleid() {
		return this.roleid;
	}

	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

	public String getPartytype() {
		return this.partytype;
	}

	public void setPartytype(String partytype) {
		this.partytype = partytype;
	}

	public Long getPartyid() {
		return this.partyid;
	}

	public void setPartyid(Long partyid) {
		this.partyid = partyid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OmPartyroleId))
			return false;
		OmPartyroleId castOther = (OmPartyroleId) other;

		return ((this.getRoleid() == castOther.getRoleid()) || (this
				.getRoleid() != null
				&& castOther.getRoleid() != null && this.getRoleid().equals(
				castOther.getRoleid())))
				&& ((this.getPartytype() == castOther.getPartytype()) || (this
						.getPartytype() != null
						&& castOther.getPartytype() != null && this
						.getPartytype().equals(castOther.getPartytype())))
				&& ((this.getPartyid() == castOther.getPartyid()) || (this
						.getPartyid() != null
						&& castOther.getPartyid() != null && this.getPartyid()
						.equals(castOther.getPartyid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRoleid() == null ? 0 : this.getRoleid().hashCode());
		result = 37 * result
				+ (getPartytype() == null ? 0 : this.getPartytype().hashCode());
		result = 37 * result
				+ (getPartyid() == null ? 0 : this.getPartyid().hashCode());
		return result;
	}

}