package com.yunda.frame.yhgl.entity;



/**
 * OmPartyrole generated by MyEclipse Persistence Tools
 * 组织对象与角色对应关系
 */

@SuppressWarnings("serial")
public class OmPartyrole implements java.io.Serializable {

	// Fields

	private OmPartyroleId id;

	// Constructors

	/** default constructor */
	public OmPartyrole() {
	}

	/** full constructor */
	public OmPartyrole(OmPartyroleId id) {
		this.id = id;
	}

	// Property accessors

	public OmPartyroleId getId() {
		return this.id;
	}

	public void setId(OmPartyroleId id) {
		this.id = id;
	}

}