package com.yunda.frame.yhgl.entity;

import java.util.Date;
import java.util.Set;

/**
 * OmPosition generated by MyEclipse Persistence Tools 岗位/职位
 */

@SuppressWarnings("serial")
public class OmPosition implements java.io.Serializable {

	// Fields

	private Long positionid; // 岗位编码

	// private OmDuty omDuty; //职务定义
	private Long dutyid;

	//private OmPosition omPosition; // 上级岗位
    private  Long manaposi;
    
	private String posicode; // 岗位代码

	private String posiname; // 岗位名称

	private Long posilevel; // 岗位层次

	private Long orgid; // 组织机构ID

	private String positionseq; // 岗位序列

	private String positype; // 岗位类别

	private Date createtime; // 创建时间

	private Date lastupdate; // 最后一次修改时间

	private Long updator; // 最近更新人员

	private Date startdate; // 岗位有效开始时间

	private Date enddate; // 岗位有效结束时间

	private String status; // 岗位状态

	private String isleaf; // 是否是叶子节点

	private Long subcount; // 子节点数
	
	private String orgname; //附加字段 机构名称（机构人员管理）
	
	private String dutyname;//附加字段 职务名称 (工作组管理)

	private Long empid; //附加字段 人员ID (人员管理-岗位调动)
	
	private String empname; //附加字段 人员姓名 (人员管理-岗位调动)
	//private Set omPositions = new HashSet(0); // 子岗位数

	// Constructors
	
	/**
	 * 说明： 在岗位表物理字段的基础上，加入了人员ID和人员名称的临时字段，在人员管理的岗位调用维护功能中用以回显数据
	 */
	public OmPosition(Long positionid, String posiname, Long empid, String empname, String isleaf){
		this.positionid = positionid;
		this.posiname = posiname;
		this.empid = empid;
		this.empname = empname;
		this.isleaf = isleaf; //利用isleaf字段，在这里作为是否是主岗位
	}
	

	/**
	 * 说明： 在岗位表物理字段的基础上，加入了机构名称和职务名称的临时字段，在机构人员管理和工作组管理中的岗位维护功能中用以回显数据
	 */
	public OmPosition(Long positionid, Long dutyid, Long manaposi, String posicode, String posiname, Long posilevel, Long orgid, String positionseq, String positype, Date createtime, Date lastupdate, Long updator, Date startdate, Date enddate, String status, String isleaf, Long subcount, String orgname, String dutyname) {
		super();
		this.positionid = positionid;
		this.dutyid = dutyid;
		this.manaposi = manaposi;
		this.posicode = posicode;
		this.posiname = posiname;
		this.posilevel = posilevel;
		this.orgid = orgid;
		this.positionseq = positionseq;
		this.positype = positype;
		this.createtime = createtime;
		this.lastupdate = lastupdate;
		this.updator = updator;
		this.startdate = startdate;
		this.enddate = enddate;
		this.status = status;
		this.isleaf = isleaf;
		this.subcount = subcount;
		this.orgname = orgname;
		this.dutyname = dutyname;
	}

	public OmPosition(Long positionid, String posiname, String posicode,
			Long orgid) {
	}

	public OmPosition(Long positionid) {
		this.positionid = positionid;
	}

	public OmPosition(String posiname, String positionseq) {
		this.posiname = posiname;
		this.positionseq = positionseq;
	}

	
	public OmPosition(Long positionid, String posiname,Long dutyid) {
		this.positionid = positionid;
		this.dutyid = dutyid;
		this.posiname = posiname;
	}
	public OmPosition(Long positionid, String posiname,Long dutyid,String isleaf) {
		this.positionid = positionid;
		this.dutyid = dutyid;
		this.posiname = posiname;
		this.isleaf = isleaf;
	}
    
	public OmPosition(Long positionid, String posiname,String positype, String isleaf) {
		
		this.positionid = positionid;
		this.posiname = posiname;
		this.isleaf = isleaf;
		this.positype = positype;
	}

	public OmPosition(Long positionid, String posicode, String posiname,
			Long orgid, String status, Long posilevel, String isleaf) {

		this.positionid = positionid;
		this.posicode = posicode;
		this.posiname = posiname;
		this.orgid = orgid;
		this.status = status;
		this.posilevel = posilevel;
		this.isleaf = isleaf;
	}

	public OmPosition(Long positionid, String posiname, String positype,
			Date startdate, Date enddate) {

		this.positionid = positionid;
		this.posiname = posiname;
		this.positype = positype;
		this.startdate = startdate;
		this.enddate = enddate;
	}

	public OmPosition() {

	}

	

	// Property accessors

	public OmPosition(Long positionid, Long dutyid, Long manaposi,
			String posicode, String posiname, Long posilevel, Long orgid,
			String positionseq, String positype, Date createtime,
			Date lastupdate, Long updator, Date startdate, Date enddate,
			String status, String isleaf, Long subcount, Set omPositions) {
		this.positionid = positionid;
		this.dutyid = dutyid;
		this.manaposi = manaposi;
		this.posicode = posicode;
		this.posiname = posiname;
		this.posilevel = posilevel;
		this.orgid = orgid;
		this.positionseq = positionseq;
		this.positype = positype;
		this.createtime = createtime;
		this.lastupdate = lastupdate;
		this.updator = updator;
		this.startdate = startdate;
		this.enddate = enddate;
		this.status = status;
		this.isleaf = isleaf;
		this.subcount = subcount;
	}

	public Long getPositionid() {
		return this.positionid;
	}

	public void setPositionid(Long positionid) {
		this.positionid = positionid;
	}

	/****
	 * public OmDuty getOmDuty() { return this.omDuty; }
	 * 
	 * public void setOmDuty(OmDuty omDuty) { this.omDuty = omDuty; }
	 ****/

	

	public Long getDutyid() {
		return dutyid;
	}

	public void setDutyid(Long dutyid) {
		this.dutyid = dutyid;
	}
	/**
	public OmPosition getOmPosition() {
		return this.omPosition;
	}
	public void setOmPosition(OmPosition omPosition) {
		this.omPosition = omPosition;
	}
    **/
	public String getPosicode() {
		return this.posicode;
	}

	public void setPosicode(String posicode) {
		this.posicode = posicode;
	}

	public String getPosiname() {
		return this.posiname;
	}

	public void setPosiname(String posiname) {
		this.posiname = posiname;
	}

	public Long getPosilevel() {
		return this.posilevel;
	}

	public void setPosilevel(Long posilevel) {
		this.posilevel = posilevel;
	}

	public Long getOrgid() {
		return this.orgid;
	}

	public void setOrgid(Long orgid) {
		this.orgid = orgid;
	}

	public String getPositionseq() {
		return this.positionseq;
	}

	public void setPositionseq(String positionseq) {
		this.positionseq = positionseq;
	}

	public String getPositype() {
		return this.positype;
	}

	public void setPositype(String positype) {
		this.positype = positype;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}
   
	public Long getManaposi() {
		return manaposi;
	}

	public void setManaposi(Long manaposi) {
		this.manaposi = manaposi;
	}

	public Date getLastupdate() {
		return this.lastupdate;
	}

	public void setLastupdate(Date lastupdate) {
		this.lastupdate = lastupdate;
	}

	public Long getUpdator() {
		return this.updator;
	}

	public void setUpdator(Long updator) {
		this.updator = updator;
	}

	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getIsleaf() {
		return this.isleaf;
	}

	public void setIsleaf(String isleaf) {
		this.isleaf = isleaf;
	}

	public Long getSubcount() {
		return this.subcount;
	}

	public void setSubcount(Long subcount) {
		this.subcount = subcount;
	}

	public String getDutyname() {
		return dutyname;
	}

	public void setDutyname(String dutyname) {
		this.dutyname = dutyname;
	}

	public String getOrgname() {
		return orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	public Long getEmpid() {
		return empid;
	}

	public void setEmpid(Long empid) {
		this.empid = empid;
	}

	public String getEmpname() {
		return empname;
	}

	public void setEmpname(String empname) {
		this.empname = empname;
	}

//	public Set getOmPositions() {
//		return this.omPositions;
//	}
//
//	public void setOmPositions(Set omPositions) {
//		this.omPositions = omPositions;
//	}

}