package com.yunda.frame.yhgl.entity;

import java.util.Date;

/**
 * OmOrganization generated by MyEclipse Persistence Tools
 * 组织机构表结构
 */

@SuppressWarnings("serial")
public class OrganizationForImport implements java.io.Serializable {
	/** 记录状态：running使用中 */
	public static final String STATUS_RUNNING = "running";
	// Fields

	private Long orgid;  //机构ID

	/*private OmOrganization omOrganization;  //父机构
	 * 
*/
	private  Long   parentorgid;   //父Id
	
	private String orgcode;  //机构代码

	private String orgname; //机构名称

	private Long orglevel; //机构层次

	private String orgdegree; //机构等级

	private String orgseq;  //机构序列

	private String orgtype;// 机构类型

	private String orgaddr; //机构地址

	private String zipcode;  //邮编

	private Long manaposition; //机构主管岗位

	private Long managerid; //机构主管人员

	private String orgmanager; //机构管理员

	private String linkman; //联系人

	private String linktel; //联系电话

	private String email;  //邮件

	private String weburl; //网站地址

	private Date startdate; //生效日期	

	private Date enddate; // 失效日期

	private String status; // 机构状态

	private String area;  // 所属地域

	private Date createtime; //创建时间	
    
	private Date lastupdate; //最近更新时间

	private Long updator; // 最近更新人

	private Long sortno; // 排列顺序编号

	private String isleaf; // 是否是叶子节点

	private Long subcount; //子节点数

	private String remark; // 备注

	private String posiname; //附加字段(机构主管岗位，来源于岗位表) 机构人员管理使用
	
	/**
	 * <li>说明：方法实现功能说明
	 * <li>创建人：谭诚
	 * <li>创建日期：2013-11-22
	 * <li>修改人： 
	 * <li>修改日期：
	 */
	public OrganizationForImport(Long orgid, Long parentorgid, String orgcode, String orgname, Long orglevel, String orgdegree, String orgseq, String orgtype, String orgaddr, String zipcode, Long manaposition, Long managerid, String orgmanager, String linkman, String linktel, String email, String weburl, Date startdate, Date enddate, String status, String area, Date createtime, Date lastupdate, Long updator, Long sortno, String isleaf, Long subcount, String remark, String posiname) {
		this.orgid = orgid;
		this.parentorgid = parentorgid;
		this.orgcode = orgcode;
		this.orgname = orgname;
		this.orglevel = orglevel;
		this.orgdegree = orgdegree;
		this.orgseq = orgseq;
		this.orgtype = orgtype;
		this.orgaddr = orgaddr;
		this.zipcode = zipcode;
		this.manaposition = manaposition;
		this.managerid = managerid;
		this.orgmanager = orgmanager;
		this.linkman = linkman;
		this.linktel = linktel;
		this.email = email;
		this.weburl = weburl;
		this.startdate = startdate;
		this.enddate = enddate;
		this.status = status;
		this.area = area;
		this.createtime = createtime;
		this.lastupdate = lastupdate;
		this.updator = updator;
		this.sortno = sortno;
		this.isleaf = isleaf;
		this.subcount = subcount;
		this.remark = remark;
		this.posiname = posiname;
	}

	/**
	 * 覆盖重写equals对象比较方法
	 */
	@Override
	public boolean equals(Object obj){
		if(obj == this)	return true;
		if (obj instanceof OrganizationForImport) {
			OrganizationForImport org = (OrganizationForImport)obj;
			if(org.getOrgid() == this.orgid)	return true;
		}
		return false;
	}	
   // private Set omOrganizations = new HashSet(0); //子机构集合

	// Constructors

	/** default constructor */
	public OrganizationForImport() {
	}
     
	public OrganizationForImport(Long orgid, String orgname) {
		this.orgid = orgid;
		this.orgname = orgname;
	}
	public OrganizationForImport(Long orgid, String orgname, String orgtype,
			String isleaf) {
		this.orgid = orgid;
		this.orgname = orgname;
		this.orgtype = orgtype;
		this.isleaf = isleaf;
	}
	
	/**
	 * 
	 * <li>说明：
	 * <li>创建人：罗鑫
	 * <li>创建日期：2011-6-22
	 * <li>修改人： 流程设置树使用
	 * <li>修改日期：
	 */
	public OrganizationForImport(Long orgid, String orgname,
			Long parentorgid,String isleaf) {
		this.orgid = orgid;
		this.orgname = orgname;
		this.parentorgid = parentorgid;
		this.isleaf = isleaf;
	}
	
	 /**
	 * 
	 * <li>说明：
	 * <li>创建人：罗鑫
	 * <li>创建日期：2011-6-22
	 * <li>修改人： 流程设置树使用
	 * <li>修改日期：
	 */
	public OrganizationForImport(Long orgid, String orgname,
			Long orglevel) {
		this.orgid = orgid;
		this.orgname = orgname;
		this.orglevel = orglevel;
	}

	/** minimal constructor */
	public OrganizationForImport(String orgcode) {
		this.orgcode = orgcode;
	}

	
	// Property accessors

	public Long getOrgid() {
		return this.orgid;
	}

	public void setOrgid(Long orgid) {
		this.orgid = orgid;
	}

	

	public String getOrgcode() {
		return this.orgcode;
	}

	public void setOrgcode(String orgcode) {
		this.orgcode = orgcode;
	}

	public String getOrgname() {
		return this.orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	public Long getOrglevel() {
		return this.orglevel;
	}

	public void setOrglevel(Long orglevel) {
		this.orglevel = orglevel;
	}

	public String getOrgdegree() {
		return this.orgdegree;
	}

	public void setOrgdegree(String orgdegree) {
		this.orgdegree = orgdegree;
	}

	public String getOrgseq() {
		return this.orgseq;
	}
	

	public void setOrgseq(String orgseq) {
		this.orgseq = orgseq;
	}

	public String getOrgtype() {
		return this.orgtype;
	}

	public void setOrgtype(String orgtype) {
		this.orgtype = orgtype;
	}

	public String getOrgaddr() {
		return this.orgaddr;
	}

	public void setOrgaddr(String orgaddr) {
		this.orgaddr = orgaddr;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public Long getManaposition() {
		return this.manaposition;
	}

	public void setManaposition(Long manaposition) {
		this.manaposition = manaposition;
	}

	public Long getManagerid() {
		return this.managerid;
	}

	public void setManagerid(Long managerid) {
		this.managerid = managerid;
	}

	public String getOrgmanager() {
		return this.orgmanager;
	}

	public void setOrgmanager(String orgmanager) {
		this.orgmanager = orgmanager;
	}

	public String getLinkman() {
		return this.linkman;
	}

	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	public String getLinktel() {
		return this.linktel;
	}

	public void setLinktel(String linktel) {
		this.linktel = linktel;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWeburl() {
		return this.weburl;
	}

	public void setWeburl(String weburl) {
		this.weburl = weburl;
	}

	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getLastupdate() {
		return this.lastupdate;
	}

	public void setLastupdate(Date lastupdate) {
		this.lastupdate = lastupdate;
	}

	public Long getUpdator() {
		return this.updator;
	}

	public void setUpdator(Long updator) {
		this.updator = updator;
	}

	public Long getSortno() {
		return this.sortno;
	}

	public void setSortno(Long sortno) {
		this.sortno = sortno;
	}

	public String getIsleaf() {
		return this.isleaf;
	}

	public void setIsleaf(String isleaf) {
		this.isleaf = isleaf;
	}

	public Long getSubcount() {
		return this.subcount;
	}

	public void setSubcount(Long subcount) {
		this.subcount = subcount;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

//	public Set getOmOrganizations() {
//		return this.omOrganizations;
//	}
//
//	public void setOmOrganizations(Set omOrganizations) {
//		this.omOrganizations = omOrganizations;
//	}

	public Long getParentorgid() {
		return parentorgid;
	}

	public void setParentorgid(Long parentorgid) {
		this.parentorgid = parentorgid;
	}

	/**
	 * <li>说明：
	 * <li>返回值： the posiname
	 */
	public String getPosiname() {
		return posiname;
	}

	/**
	 * <li>说明：
	 * <li>参数： posiname
	 */
	public void setPosiname(String posiname) {
		this.posiname = posiname;
	}

	

}